import { RouterProvider, createRouter } from '@tanstack/react-router';

import { trackEvent } from '@/lib/analytics/trackEvent';

// Import the generated route tree (auto-generated by TanStack Router Vite plugin)
import { routeTree } from './routeTree.gen';

// Create a new router instance
const router = createRouter({ routeTree });

// Track pageviews on navigation (module-level avoids React Strict Mode double-mount)
let lastPath = '';
const trackPageView = () => {
  const path = router.history.location.pathname;
  if (path === lastPath) return;
  lastPath = path;
  void trackEvent({ type: 'pageview', path });
};
trackPageView(); // Initial load
router.history.subscribe(trackPageView); // Navigation

// Register the router instance for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

function App() {
  return <RouterProvider router={router} />;
}

export default App;
