import { RouterProvider, createRouter } from '@tanstack/react-router';

// Import the generated route tree (auto-generated by TanStack Router Vite plugin)
import { routeTree } from './routeTree.gen';

// Create a new router instance
const router = createRouter({ routeTree });

// Register the router instance for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

function App() {
  return <RouterProvider router={router} />;
}

export default App;
