import { RouterProvider, createRouter } from '@tanstack/react-router';
import { useEffect } from 'react';

import { trackEvent } from '@/lib/analytics/trackEvent';

// Import the generated route tree (auto-generated by TanStack Router Vite plugin)
import { routeTree } from './routeTree.gen';

// Create a new router instance
const router = createRouter({ routeTree });

let lastPath = '';
const trackPageView = () => {
  const path = router.history.location.pathname;
  if (path === lastPath) return;
  lastPath = path;
  void trackEvent({ type: 'pageview', path });
};

// Register the router instance for type safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

function App() {
  useEffect(() => {
    trackPageView();
    return router.history.subscribe(trackPageView);
  }, []);

  return <RouterProvider router={router} />;
}

export default App;
